import { Heart, MessageCircle, Send, UserRound, X } from 'lucide-react'
import { useEffect, useState } from 'react'
import { commentKnowledge, commentProject, getKnowledgeComments, getProjectComments, likeKnowledge, likeProject, registerGuest, unlikeKnowledge, unlikeProject } from '../../services/portfolioApi'

export function EngagementPanel({ type, id, initialLikes = 0 }) {
  const api = type === 'knowledge' ? { comments: getKnowledgeComments, comment: commentKnowledge, like: likeKnowledge, unlike: unlikeKnowledge } : { comments: getProjectComments, comment: commentProject, like: likeProject, unlike: unlikeProject }
  const [comments,setComments]=useState([]),[content,setContent]=useState(''),[liked,setLiked]=useState(false),[likes,setLikes]=useState(initialLikes),[identity,setIdentity]=useState(false),[guest,setGuest]=useState({displayName:'',email:''}),[notice,setNotice]=useState('')
  useEffect(()=>{api.comments(id).then(setComments).catch(()=>{})},[id,type])
  async function toggleLike(){try{const result=liked?await api.unlike(id):await api.like(id);setLiked(result.liked);setLikes(result.likeCount)}catch{setIdentity(true)}}
  async function submit(e){e.preventDefault();if(!content.trim())return;try{const result=await api.comment(id,{content});setContent('');setNotice(result.status==='PENDING'?'Bình luận đã gửi và đang chờ duyệt.':'Đã đăng bình luận.')}catch{setIdentity(true)}}
  async function register(e){e.preventDefault();await registerGuest(guest);setIdentity(false);setNotice('Đã ghi nhớ thông tin. Bạn có thể tương tác ngay.')}
  return <section className="engagement"><div className="engagement-head"><div><span>COMMUNITY</span><h2>Yêu thích & thảo luận</h2></div><button className={liked?'liked':''} onClick={toggleLike}><Heart fill={liked?'currentColor':'none'}/><b>{likes}</b> Yêu thích</button></div><form className="comment-form" onSubmit={submit}><div className="comment-avatar"><UserRound/></div><textarea maxLength="3000" placeholder="Chia sẻ suy nghĩ của bạn…" value={content} onChange={e=>setContent(e.target.value)}/><button><Send/>Gửi</button></form>{notice&&<p className="engagement-notice">{notice}</p>}<div className="comment-list"><h3><MessageCircle/>{comments.length} bình luận</h3>{comments.length===0?<p>Chưa có bình luận được duyệt. Hãy là người đầu tiên chia sẻ!</p>:comments.map(c=><article key={c.id}><div>{c.displayName.charAt(0)}</div><section><header><b>{c.displayName}</b>{c.emailVerified&&<span>Đã xác minh</span>}<time>{new Date(c.createdAt).toLocaleDateString('vi-VN')}</time></header><p>{c.content}</p></section></article>)}</div>{identity&&<div className="identity-modal"><form onSubmit={register}><button type="button" onClick={()=>setIdentity(false)}><X/></button><div className="identity-icon"><UserRound/></div><h3>Thông tin khách</h3><p>Chỉ cần nhập một lần, không cần tạo tài khoản hoặc mật khẩu.</p><label>Tên hiển thị<input required maxLength="150" value={guest.displayName} onChange={e=>setGuest({...guest,displayName:e.target.value})}/></label><label>Email<input required type="email" value={guest.email} onChange={e=>setGuest({...guest,email:e.target.value})}/></label><button className="identity-submit">Tiếp tục tương tác</button><small>Email không hiển thị công khai.</small></form></div>}</section>
}
